baseURL = 'https://jriver.xyz/'
languageCode = 'en-us'
title = 'JRiver Blog'
theme = 'hugo-blog-awesome'

[[params.socialIcons]]
name = "github"
url = "https://github.com/hugo-sid"

[[params.socialIcons]]
name = "gitlab"
url = "index.xml"

[[params.socialIcons]]
name = "linkedin"
url = "https://twitter.com"

[params]
  goToTop = true




